version: "3.9"

services:

  airis_be:
    build: ./backend
    container_name: airis_be
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - airis_pg
      - airis_influx

  airis_fe:
    build: ./frontend
    container_name: airis_fe
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - airis_be

  airis_pg:
    image: postgres:16
    container_name: airis_pg
    restart: always
    environment:
      POSTGRES_USER: AIRIS_ADMIN
      POSTGRES_PASSWORD: InisebuahPassword14
      POSTGRES_DB: airisdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  airis_influx:
    image: influxdb:2.7
    container_name: airis_influx
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: AIRIS_ADMIN
      DOCKER_INFLUXDB_INIT_PASSWORD: InisebuahPassword14
      DOCKER_INFLUXDB_INIT_ORG: airisorg
      DOCKER_INFLUXDB_INIT_BUCKET: airisbucket
      DOCKER_INFLUXDB_INIT_RETENTION: 0
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: base64:KD2Zlxu45NvM8auMJihGLxR/4qfbobr+tX2SE+CLb3c=
    volumes:
      - influx_data:/var/lib/influxdb2

volumes:
  postgres_data:
  influx_data: