// FILE CONTROLLER UNTUK CREATE, READ, UPDATE, DAN DELETE KONTEN WEB
// TABEL DATABASE YANG DIPAKAI YANG WEBCONTENT YAAA
const prisma = require("../lib/prisma");

exports.createContent = async (req, res) => {
    // ISI FUNGSINYA UNTUK MENAMBAH DATA KE TABEL WEBCONTENT
}

exports.updateContent = async (req, res) => {
    // ISI FUNGSINYA UNTUK MENGEDIT DATA YANG SUDAH ADA DI TABEL WEBCONTENT
}

exports.deleteContent = async (req, res) => {
    // ISI FUNGSINYA UNTUK MENGHAPUS DATA YANG ADA DI TABEL WEBCONTENT
}

// KALAU SUDAH SELESAI KE FOLDER ROUTES FILE CONTENTROUTES.JS YAA
