// FILE UNTUK ROUTING FUNGSI KONTEN WEB
const express = require("express");
const router = express.Router();
// TULIS KODE UNTUK REQUIRE FILE CONTENTCONTROLLER.JS DISINI

// TULIS KODE-KODE UNTUK ROUTING MASING-MASING FUNGSI KONTEN (CREATE, UPDATE, DAN DELETE)

module.exports = router;

// KALAU SUDAH SELESAI KE FILE APP.JS